language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '6'
before_install:
  - npm install -g cypress-cli
script:
  - npm test
  - npm run build
  - cypress ci
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
